name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Checar arquivos estáticos
        run: |
          ls -R
          echo "Todos os arquivos foram carregados no Runner!"

          - name: Checar arquivos estáticos
     