name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Checar arquivos estáticos
        run: |
          ls -R
          echo "Todos os arquivos foram carregados no Runner!"

      - name: Instalar HTMLHint
        run: npm install -g htmlhint

      - name: Validar sintaxe do HTML
        run: htmlhint index.html